#!/bin/sh
#
# Script for hem, home environment monitor.
# C2015 Xun Jiang

### BEGIN INIT INFO
# Provides:        hem
# Required-Start:  $remote_fs $syslog
# Required-Stop:   $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start hem daemon
# Description:       Starts and stops the hem daemon used to
#                    read and log home environment data from multiple sensors.
### END INIT INFO

if [ -f /etc/default/hem ]; then
    . /etc/default/hem
else
    echo "No configuration file found."
#    exit 0
fi

if [ "$HEM_DAEMON" = "no" ]; then
    echo "hem is disabled. Please, see /etc/default/hem."
#    exit 0
fi

HEMD_PYM="/home/pi/hem/hem.py"
HEMSERVER_PYM="/home/pi/hem/site/hemServer.py"
HEMD_PIDFILE="/var/run/hem.pid"
HEMSERVER_PIDFILE="/var/run/hemserver.pid"
HEMSERVER_LOGFILE="/home/pi/hem/site/hemServer.log"
HEM_BT_APMI_PIDFILE="/var/run/hemapmi.pid"
HEM_BT_APMI_ADDR="98:D3:32:30:39:59"

case "$1" in
	start)
		echo "Starting hem daemon and hem web server"
		# Add delay here to allow time initialization via htpdate
		$HEMD_PYM &
		HEMD_PID=$!
		echo $HEMD_PID > $HEMD_PIDFILE
		$HEMSERVER_PYM > $HEMSERVER_LOGFILE &
		HEMSERVER_PID=$!
		echo $HEMSERVER_PID > $HEMSERVER_PIDFILE
		rfcomm connect hci0 $HEM_BT_APMI_ADDR &
		HEM_BT_APMI_PID=$!
		echo $HEM_BT_APMI_PID > $HEM_BT_APMI_PIDFILE
		;;
	stop)
		echo "Stopping hem daemon and hem web server"
		if [ -f $HEM_BT_APMI_PIDFILE ]; then
			kill -INT `cat $HEM_BT_APMI_PIDFILE`
		else
			echo "$HEM_BT_APMI_PIDFILE not found"
		fi
		if [ -f $HEMD_PIDFILE ]; then
			kill `cat $HEMD_PIDFILE`
		else
			echo "$HEMD_PIDFILE not found"
		fi
		rm -f $HEMD_PIDFILE 
                if [ -f $HEMSERVER_PIDFILE ]; then
                        kill `cat $HEMSERVER_PIDFILE`
                else
                        echo "$HEMSERVER_PIDFILE not found"
                fi
		rm -f $HEMSERVER_PIDFILE
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
